### ISSUE TITLE
No result problem

### ISSUE THREAD

**Issue by guyuemochen** [Glavo/rcon-java#1]
When I was trying to work with this, the first command sent to the server cannot receive any feedback. However, after that the responses are correct. Can you fix this? Thx

**Comment by Glavo** [comment]
> When I was trying to work with this, the first command sent to the server cannot receive any feedback. However, after that the responses are correct. Can you fix this? Thx

I can't reproduce this problem, it works well with me. Can you give more operating status?

Can you tell me the detailed operating environment? I'll try to reproduce it.
