### ISSUE TITLE
slow or non-responsive server causes library to hang

### ISSUE THREAD

**Issue by LiamFry** [Glavo/rcon-java#2]
I can't find anything that allows me to set a timeout for socket IO. I'm using `rcon-java` as a library and my app isn't interactive in any way, i.e. there's no human on standby. There's always a chance the remote service (which I have no control over) is in such a state that it's up but not running properly. My `RCON` connection is accepted by the server but the server never responds to the authentication sequence. This sort of non-responsiveness from the server can also happen mid-stream: after authentication and a period of successful transmissions, the server either loses its mind or becomes overloaded and can't respond in a timely fashion. Since there's no timeout feature (that I can find) in the `rcon-java` library, my application ends up moving in lock-step with the server; if the server is fine, I'm fine but if the server hangs, I hang.

Would it be possible to add a "timeout" parameter to the `Rcon` constructor that applies to all socket `connect()`, `send()`, and `receive()` operations?

**Comment by Glavo** [comment]
Java's `Sockets` don't support timeouts when written, and I think maybe I need to refactor all my code.

**Comment by Glavo** [comment]
I released rcon-java 3.0 which adds a new API: `Rcon::setTimeout(int)`. You can set the timeout for connecting and reading by calling this method.

Besides that, rcon-java is now published on Maven Central, so you no longer need to add the jitpack repository.

**Comment by LiamFry** [comment]
Great! I already get it from Maven Central but MC is showing v2.0.2 dated 10-Dec-2020 as the latest. [RCON Java](https://mvnrepository.com/artifact/org.glavo/rcon-java)](https://mvnrepository.com/artifact/org.glavo/rcon-java)

Am I perhaps using the wrong name in Maven Central?

**Comment by Glavo** [comment]
> Great! I already get it from Maven Central but MC is showing v2.0.2 dated 10-Dec-2020 as the latest. [RCON Java](https://mvnrepository.com/artifact/org.glavo/rcon-java)](https://mvnrepository.com/artifact/org.glavo/rcon-java)
> 
> Am I perhaps using the wrong name in Maven Central?

There is a delay on this page (maybe one to two days). The most timely way to check for new versions is to visit the Maven Central repository directly: https://repo1.maven.org/maven2/org/glavo/rcon-java/
